### ISSUE TITLE
挺有用的小工具，但是仍然有部分文件无法删除

### ISSUE THREAD

**Issue by dongyi945** [differentrain/Delapp#1]
路径的形式不合法。System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 DelApp.Internals.SoundPlayHelper.DisposeManaged()
   在 DelApp.Internals.DisposableSingleton`1.System.IDisposable.Dispose()
   在 DelApp.Program.Main()路径的形式不合法。

感觉还是文件权限的问题，删除不了的文件只有system账号有修改权限。

**Comment by differentrain** [comment]
异常问题应该已经修复。
关于文件删除问题，雀食。获取system权限的话，一来单文件应用做不到，二来有些危险，三来会影响一些系统路径（比如个人文件夹位置），所以放弃了。
